# Generated by Django 2.1 on 2018-10-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('price', models.CharField(max_length=256, null=True)),
                ('area', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(null=True)),
                ('sell_date', models.TextField(null=True)),
                ('expired_date', models.TextField(null=True)),
                ('website_uuid', models.CharField(max_length=256, null=True)),
                ('seller_name', models.CharField(max_length=256, null=True)),
                ('seller_address', models.CharField(max_length=256, null=True)),
                ('seller_phone', models.CharField(max_length=256, null=True)),
                ('seller_mobile', models.CharField(max_length=256, null=True)),
                ('seller_email', models.CharField(max_length=256, null=True)),
                ('seller_picture', models.TextField(null=True)),
                ('project_name', models.CharField(max_length=256, null=True)),
                ('project_investor', models.CharField(max_length=256, null=True)),
                ('extended_data', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='ArticlePicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article')),
            ],
            options={
                'verbose_name': 'ArticlePicture',
                'verbose_name_plural': 'ArticlePicture',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('url', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Website',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='website',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Website'),
        ),
    ]
