# Generated by Django 2.1 on 2018-10-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='website',
            field=models.ForeignKey(db_column='website', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Website'),
        ),
        migrations.AlterField(
            model_name='articlepicture',
            name='article_id',
            field=models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, to='api.Article'),
        ),
    ]
