# Generated by Django 2.1 on 2018-10-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181024_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='form',
            new_name='name',
        ),
    ]
